version: '3.8'

services:
  backend:
    build:
      context: ./cmd
    ports:
      - "5050:5050"
    networks:
      - app-network

  frontend:
    build:
      context: ./static
    ports:
      - "8080:80"
    networks:
      - app-network